apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

labels:
  - pairs:
      api.kmontocam.com: "true"
      kmontocam.com/project: home
      kmontocam.com/environment: prod
    includeTemplates: true

patches:
  - target:
      version: v1
      kind: Deployment
    path: ./deployment.yaml

secretGenerator:
  - name: kmontocam-backend
    namespace: kmontocam
    envs:
      - .env # must include DATABASE_URL
generatorOptions:
  disableNameSuffixHash: true
