apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kmontocam-backend
  name: kmontocam-backend
  namespace: kmontocam
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kmontocam-backend
  template:
    metadata:
      annotations:
        fluentbit.io/exclude_stderr-axum: "true"
        fluentbit.io/parser_stdout-axum: logfmt
      labels:
        app: kmontocam-backend
        devops.kmontocam.com/parse-logs: "true"
    spec:
      containers:
        - env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  key: DATABASE_URL
                  name: kmontocam-backend
          image: ghcr.io/kmontocam/kmontocam.com-backend:latest
          imagePullPolicy: Always
          name: axum
          ports:
            - containerPort: 3000
              name: http
              protocol: TCP
          resources:
            limits:
              cpu: 100m
              memory: 64Mi
            requests:
              cpu: 50m
              memory: 32Mi
      nodeSelector:
        kubernetes.io/os: linux
